FROM alpine:latest

# Install dependencies for PocketBase
RUN apk add --no-cache \
    unzip \
    ca-certificates

ARG PB_VERSION=0.22.11

# Download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

# Migrate structure into volume
COPY ./pocketbase/pb_migrations /pb/pb_migrations

# Migrate data into volume
COPY ./pocketbase/pb_data /pb/pb_data

# Expose the port for PocketBase
EXPOSE 8090

# Start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8090"]

